Saving last configuration file to .certora_internal/24_05_20_09_52_18_284/run.conf
There is no TAC file. Going to script EVMVerifier/certoraBuild.py to main_with_args()
Creating dir /home/user/new_labs/labs/task/.certora_internal/24_05_20_09_52_18_284/.certora_config
In /home/user/new_labs/labs/task/sisters.spec, found the imports: []
copying spec file /home/user/new_labs/labs/task/sisters.spec to /home/user/new_labs/labs/task/.certora_internal/24_05_20_09_52_18_284/.certora_sources/.0_sisters.spec.spec
writing /home/user/new_labs/labs/task/.certora_internal/24_05_20_09_52_18_284/.certora_verify.json
Path to typechecker is /home/user/new_labs/labs/certora-beta/lib/python3.10/site-packages/certora_jars/Typechecker.jar
running ['java', '-jar', '/home/user/new_labs/labs/certora-beta/lib/python3.10/site-packages/certora_jars/Typechecker.jar', '-buildDirectory', '/home/user/new_labs/labs/task/.certora_internal/24_05_20_09_52_18_284', '-rule', 'sistersBirthMonths']

building file Empty.sol
Running cmd solc --version
stdout, stderr = .certora_internal/24_05_20_09_52_18_284/.certora_config/version_check_solc.stdout, .certora_internal/24_05_20_09_52_18_284/.certora_config/version_check_solc.stderr
build failed
Failure traceback: 
Exception: Failed to run solc --version, exit code 1
Encountered an error running Certora Prover, please contact Certora; consider running the script again with --debug to find out why it failed
