Saving last configuration file to .certora_internal/24_05_20_10_11_40_942/run.conf
There is no TAC file. Going to script EVMVerifier/certoraBuild.py to main_with_args()
Creating dir /home/user/new_labs/labs/task/.certora_internal/24_05_20_10_11_40_942/.certora_config
In /home/user/new_labs/labs/task/sisters.spec, found the imports: []
copying spec file /home/user/new_labs/labs/task/sisters.spec to /home/user/new_labs/labs/task/.certora_internal/24_05_20_10_11_40_942/.certora_sources/.0_sisters.spec.spec
writing /home/user/new_labs/labs/task/.certora_internal/24_05_20_10_11_40_942/.certora_verify.json
Path to typechecker is /home/user/new_labs/labs/certora-beta/lib/python3.10/site-packages/certora_jars/Typechecker.jar
running ['java', '-jar', '/home/user/new_labs/labs/certora-beta/lib/python3.10/site-packages/certora_jars/Typechecker.jar', '-buildDirectory', '/home/user/new_labs/labs/task/.certora_internal/24_05_20_10_11_40_942', '-rule', 'sistersBirthMonths']

building file Empty.sol
Running cmd solc --version
stdout, stderr = .certora_internal/24_05_20_10_11_40_942/.certora_config/version_check_solc.stdout, .certora_internal/24_05_20_10_11_40_942/.certora_config/version_check_solc.stderr
Exitcode 0
Solc run solc --version time: 0.0519
Running cmd solc -o ".certora_internal/24_05_20_10_11_40_942/.certora_config/Empty.sol_0/" --overwrite --allow-paths ".",. --standard-json
stdout, stderr = .certora_internal/24_05_20_10_11_40_942/.certora_config/Empty.sol_0.standard.json.stdout, .certora_internal/24_05_20_10_11_40_942/.certora_config/Empty.sol_0.standard.json.stderr
Exitcode 0
Solc run solc -o ".certora_internal/24_05_20_10_11_40_942/.certora_config/Empty.sol_0/" --overwrite --allow-paths ".",. --standard-json time: 0.0471
reading standard json data from .certora_internal/24_05_20_10_11_40_942/.certora_config/Empty.sol_0.standard.json.stdout
collecting worklist for /home/user/new_labs/labs/task/Empty.sol
Processing dependencies from file /home/user/new_labs/labs/task/Empty.sol
build failed
Failure traceback: 
KeyError: 'contracts'
Encountered an error running Certora Prover, please contact Certora; consider running the script again with --debug to find out why it failed
